# Generated by Django 5.0 on 2024-01-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100000)),
                ('blog_description', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blogs')),
            ],
        ),
    ]
